---
  - name: list all files in {{ file_path }}
    tags:
      - clean
    find: paths={{ file_path }} patterns="*" hidden=True
    register: delete_file_list
  - name: delete listed files
    tags:
      - clean
    file: path={{ item.path }} state=absent
    with_items:
    - "{{ delete_file_list.files }}"
...
